spring:
  main:
    web-application-type: reactive
    lazy-initialization: true
  application:
    name: Aplikasi Test
  config:
    activate:
      on-profile: dev
  jackson:
    time-zone: Asia/Jakarta
application:
  security:
    validasi: 360000
    remember-me: 1000000
    refreshDateInMs: 360000
    # untuk generate key silahkan gunakan command openssl rand -base64 64
    secret: vHPJST0lessUGvH/W8HVlihERtV4OWMSkseiDm/1/K/BPfvuyjr9JEqHsBPTpZatg4fx+ywtV7xb13zE0p8lTQ==
logging:
  level:
    ROOT: ERROR
    com.jasavast: DEBUG
    org.springframework.data.r2dbc.core: DEBUG